WITH all_matches AS (
    SELECT * FROM SOCCER.TBL_UEFA_2020
    UNION ALL
    SELECT * FROM SOCCER.TBL_UEFA_2021
    UNION ALL
    SELECT * FROM SOCCER.TBL_UEFA_2022
),
all_shots AS (
    SELECT 
        TEAM_NAME_HOME AS TEAM, 
        TOTAL_SHOTS_HOME AS SHOTS,
        SHOTS_ON_TARGET_HOME AS TARGETS
    FROM all_matches

    UNION ALL

    SELECT 
        TEAM_NAME_AWAY AS TEAM, 
        TOTAL_SHOTS_AWAY AS SHOTS,
        SHOTS_ON_TARGET_AWAY AS TARGETS
    FROM all_matches
),
team_total_shots AS (
    SELECT 
        TEAM,
        SUM(SHOTS) AS TOTAL_SHOTS,
        SUM(TARGETS) AS TOTAL_TARGETS
    FROM all_shots
    GROUP BY TEAM
)
SELECT
    TEAM,
    TOTAL_TARGETS,
    TOTAL_SHOTS,
    ROUND(TOTAL_TARGETS / NULLIF(TOTAL_SHOTS, 0), 3) AS EFFICIENCY
FROM team_total_shots
ORDER BY EFFICIENCY DESC;
