WITH all_matches AS (
    SELECT '2020' AS SEASON, * FROM SOCCER.TBL_UEFA_2020
    UNION ALL
    SELECT '2021' AS SEASON, * FROM SOCCER.TBL_UEFA_2021
    UNION ALL
    SELECT '2022' AS SEASON, * FROM SOCCER.TBL_UEFA_2022
),
majority_possession AS (
    SELECT 
        SEASON,
        CASE 
            WHEN POSSESSION_HOME > POSSESSION_AWAY THEN TEAM_NAME_HOME
            WHEN POSSESSION_AWAY > POSSESSION_HOME THEN TEAM_NAME_AWAY
            ELSE NULL
        END AS TEAM_WITH_MAJORITY_POSSESSION
    FROM all_matches
),
filtered AS (
    SELECT * FROM majority_possession
    WHERE TEAM_WITH_MAJORITY_POSSESSION IS NOT NULL
),
ranked AS (
    SELECT 
        SEASON,
        TEAM_WITH_MAJORITY_POSSESSION AS TEAM_NAME,
        COUNT(*) AS GAME_COUNT,
        RANK() OVER (PARTITION BY SEASON ORDER BY COUNT(*) DESC) AS team_rank
    FROM filtered
    GROUP BY SEASON, TEAM_WITH_MAJORITY_POSSESSION
)

SELECT 
    SEASON,
    TEAM_NAME,
    GAME_COUNT
FROM ranked
WHERE team_rank = 1
ORDER BY SEASON;
