-- View: VIEW_TEAM_POSSESSION_ANALYSIS
-- Description: Identifies the team with majority possession in each match across all seasons.
-- Data Source: TBL_UEFA_2020, TBL_UEFA_2021, TBL_UEFA_2022
-- Dependencies: Requires possession fields and team names.

CREATE VIEW VIEW_TEAM_POSSESSION_ANALYSIS AS
WITH all_matches AS (
    SELECT '2020' AS SEASON, * FROM SOCCER.TBL_UEFA_2020
    UNION ALL
    SELECT '2021' AS SEASON, * FROM SOCCER.TBL_UEFA_2021
    UNION ALL
    SELECT '2022' AS SEASON, * FROM SOCCER.TBL_UEFA_2022
)
SELECT
    SEASON,
	STAGE,
    DATE,
    TEAM_NAME_HOME,
    TEAM_NAME_AWAY,
    POSSESSION_HOME,
    POSSESSION_AWAY,
    CASE 
        WHEN POSSESSION_HOME > POSSESSION_AWAY THEN TEAM_NAME_HOME
        WHEN POSSESSION_AWAY > POSSESSION_HOME THEN TEAM_NAME_AWAY
        ELSE NULL
    END AS TEAM_WITH_MAJORITY_POSSESSION
FROM all_matches
WHERE POSSESSION_HOME <> POSSESSION_AWAY;
