-- View: VIEW_DUEL_LOSSES_BY_STAGE
-- Description: Captures matches where a team won more duels but still lost the match, broken down by stage.
-- Data Source: TBL_UEFA_2020, TBL_UEFA_2021, TBL_UEFA_2022
-- Dependencies: Requires duels fields and team names.
CREATE VIEW VIEW_DUEL_LOSSES_BY_STAGE AS
WITH all_matches AS (
    SELECT '2020' AS SEASON, * FROM SOCCER.TBL_UEFA_2020
    UNION ALL
    SELECT '2021' AS SEASON, * FROM SOCCER.TBL_UEFA_2021
    UNION ALL
    SELECT '2022' AS SEASON, * FROM SOCCER.TBL_UEFA_2022
)
SELECT
    SEASON,
    STAGE,
	DATE,
    TEAM_NAME_HOME,
    TEAM_NAME_AWAY,
	DUELS_WON_HOME,
	DUELS_WON_AWAY,
    CASE 
    	WHEN DUELS_WON_HOME > DUELS_WON_AWAY AND TEAM_HOME_SCORE < TEAM_AWAY_SCORE THEN TEAM_NAME_HOME
        WHEN DUELS_WON_AWAY > DUELS_WON_HOME AND TEAM_AWAY_SCORE < TEAM_HOME_SCORE THEN TEAM_NAME_AWAY
        ELSE NULL
        END AS TEAM_LOST
FROM all_matches
WHERE TEAM_LOST IS NOT NULL;
