WITH all_matches AS (
    SELECT * FROM SOCCER.TBL_UEFA_2020
    UNION ALL
    SELECT * FROM SOCCER.TBL_UEFA_2021
    UNION ALL
    SELECT * FROM SOCCER.TBL_UEFA_2022
),
match_prediction_vs_actual AS (
  SELECT
	*,
    CASE
      WHEN PREDICTION_TEAM_HOME_WIN > PREDICTION_DRAW AND PREDICTION_TEAM_HOME_WIN > PREDICTION_TEAM_AWAY_WIN THEN 'HOME_WIN'
      WHEN PREDICTION_TEAM_AWAY_WIN > PREDICTION_TEAM_HOME_WIN AND PREDICTION_TEAM_AWAY_WIN > PREDICTION_DRAW THEN 'AWAY_WIN'
      ELSE 'DRAW'
    END AS PREDICTED_RESULT,

    CASE
      WHEN TEAM_HOME_SCORE > TEAM_AWAY_SCORE THEN 'HOME_WIN'
      WHEN TEAM_HOME_SCORE < TEAM_AWAY_SCORE THEN 'AWAY_WIN'
      ELSE 'DRAW'
    END AS ACTUAL_RESULT
  FROM all_matches
),
team_results AS (
  SELECT
    TEAM_NAME_HOME AS TEAM_NAME,
    'HOME' AS SIDE,
    PREDICTED_RESULT,
    ACTUAL_RESULT,
    CASE
      WHEN PREDICTED_RESULT = 'HOME_WIN' THEN 'WIN'
      WHEN PREDICTED_RESULT = 'AWAY_WIN' THEN 'LOSS'
      ELSE 'DRAW'
    END AS PREDICTED_OUTCOME,
    CASE
      WHEN TEAM_HOME_SCORE > TEAM_AWAY_SCORE THEN 'WIN'
      WHEN TEAM_HOME_SCORE < TEAM_AWAY_SCORE THEN 'LOSS'
      ELSE 'DRAW'
    END AS ACTUAL_OUTCOME
  FROM match_prediction_vs_actual

  UNION ALL

  SELECT
    TEAM_NAME_AWAY AS TEAM_NAME,
    'AWAY' AS SIDE,
    PREDICTED_RESULT,
    ACTUAL_RESULT,
    CASE
      WHEN PREDICTED_RESULT = 'AWAY_WIN' THEN 'WIN'
      WHEN PREDICTED_RESULT = 'HOME_WIN' THEN 'LOSS'
      ELSE 'DRAW'
    END AS PREDICTED_OUTCOME,
    CASE
      WHEN TEAM_AWAY_SCORE > TEAM_HOME_SCORE THEN 'WIN'
      WHEN TEAM_AWAY_SCORE < TEAM_HOME_SCORE THEN 'LOSS'
      ELSE 'DRAW'
    END AS ACTUAL_OUTCOME
  FROM match_prediction_vs_actual
),
accuracy_check AS (
  SELECT *,
         CASE WHEN PREDICTED_OUTCOME = ACTUAL_OUTCOME THEN 1 ELSE 0 END AS IS_CORRECT
  FROM team_results
)
SELECT 
	TEAM_NAME,
	COUNT(*) AS TOTAL_MATCHES,
	SUM(IS_CORRECT) AS CORRECT_PREDICTIONS,
	ROUND(SUM(IS_CORRECT) / COUNT(*), 3) AS ACCURACY
FROM accuracy_check
GROUP BY TEAM_NAME
ORDER BY ACCURACY DESC;
